version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - "5433:5432"  # host:container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task_manager_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "bundle exec rails db:prepare && rails server -b 0.0.0.0 -p 8080"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/task_manager_development

volumes:
  postgres_data:
