default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>


test:
  <<: *default
  database: task_manager_test
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV["DB_PASSWORD"] %>
  database: task_manager_production
  host: "/cloudsql/task-manager-mario-dev:us-central1:task-manager-db"
